# Settings
- defaults:
    link:
      create: true
      relink: true
      force: true # Swap original file

# TODO: ?
- clean: ["~"]

# Run shell commands
- shell:
    # Install submodules
    - [git submodule update --init --recursive, Installing submodules]

# TODO: add specific shell block to install tools (not sure how)
#- shell:
# TODO: delete! probably dont need it
#- npm config set prefix '~/.npm-global'
# TODO: Automate filling in the list
# TODO: Install go tools
#- go get -u github.com/m3ng9i/ran
# TODO: Install rust
# TODO: Install npm global tools
#- npm install -g @fabiospampinato/bump
- go:
    - github.com/delicb/cliware

- rust:
    - stable:
        - targets:
            - x86_64-apple-darwin
            - x86_64-unknown-linux-gnu
        - components:
            - rust-analysis
            - rls
            - rust-src
- cargo:
    - cargo-watch
    - racer:
      - +nightly

# Install asdf
- asdf:
    - plugin: python
      url: https://github.com/tuvistavie/asdf-python.git
      global: anaconda3-5.3.1
      versions:
        - anaconda3-5.3.1
    - plugin: nodejs
      url: https://github.com/asdf-vm/asdf-nodejs.git
      global: 12.15.0
      versions:
        - 12.15.0
    - plugin: ruby
      url: https://github.com/asdf-vm/asdf-ruby.git
      global: 2.6.4
      versions:
        - 2.6.4
    - plugin: golang
      url: https://github.com/kennyp/asdf-golang
      global: 1.12.1
      versions:
        - 1.12.1
    - plugin: elixir
      url: https://github.com/asdf-vm/asdf-elixir.git
      global: 1.10.1
      versions:
        - 1.10.1

- vscodefile:
    # vscodefile
    file: vscode/vscodefile
    insiders: false

- brewfile:
    # This accepts the same options as `brew bundle` command:
    file: macos/Brewfile

# Symlink files
- link:
    # bin
    ~/.bin:
      create: true
      path: bin
    ~/.bin/airport: /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport
    # Zsh
    ~/.zshrc:
      force: true
      path: zsh/zshrc.zsh
    ~/.zshrc.d:
      create: true
      path: zsh/
    ~/.zlogin: zsh/zlogin
    ~/.zshenv: zsh/zshenv
    ~/.zshkeys: zsh/zshkeys
    ~/.tmux.conf: tmux/tmux.conf
    ~/.tmux.conf.local: tmux/tmux.conf.local
    ~/.fonts:
      create: true
      path: local/fonts/SourceCodePro
    ~/.emacs.d:
      path: emacs/spacemacs
    ~/.spacemacs: emacs/spacemacs.conf

    ~/.zshrc: zsh/zshrc.zsh
    ~/.zprofile: zsh/zprofile.zsh
    # Git
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
    # antibody
    ~/.antibody: config/antibody.txt
    # Hammerspoon
    ~/.hammerspoon: hammerspoon
    # hyper.js
    ~/.hyper.js: config/hyper.js
    # Neovim
    ~/.config/nvim: nvim
    # VS Code
    ~/Library/Application Support/Code/User/settings.json: vscode/settings.json
    ~/Library/Application Support/Code/User/keybindings.json: vscode/keybindings.json
    # IDEA
    ~/.ideavimrc: idea/ideavimrc
