# Settings
- defaults:
    link:
      create: true
      relink: true
      force: true # Swap original file

# TODO: ?
- clean: ["~", "~/.config"]

# Run shell commands
- shell:
    # Install submodules
    - [git submodule update --init --recursive, Installing submodules]

# TODO: add specific shell block to install tools (not sure how)
#- shell:
# TODO: delete! probably dont need it
#- npm config set prefix '~/.npm-global'
# TODO: Automate filling in the list
# TODO: Install go tools
#- go get -u github.com/m3ng9i/ran
# TODO: Install rust
# TODO: Install npm global tools
#- npm install -g @fabiospampinato/bump
- asdf:
    - plugin: python
      url: https://github.com/tuvistavie/asdf-python.git
      global: 3.8.1
      versions:
        - 3.8.1
    - plugin: nodejs
      url: https://github.com/asdf-vm/asdf-nodejs.git
      global: 12.10
      versions:
        - 12.10
    - plugin: ruby
      url: https://github.com/asdf-vm/asdf-ruby.git
      global: 2.6.4
      versions:
        - 2.6.4
    - plugin: golang
      url: https://github.com/kennyp/asdf-golang
      global: 1.12.1
      versions:
        - 1.12.1

- vscodefile:
    file: vscode/vscodefile

# Symlink files
- link:
    # Zsh
    ~/.zshrc: zsh/zshrc.zsh
    ~/.zprofile: zsh/zprofile.zsh
    # Git
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
    # antibody
    ~/.antibody: config/antibody.txt
    # Hammerspoon
    ~/.hammerspoon: hammerspoon
    # hyper.js
    ~/.hyper.js: config/hyper.js
    # Neovim
    ~/.config/nvim: nvim
    # VS Code
    ~/Library/Application Support/Code/User/settings.json: vscode/settings.json
    ~/Library/Application Support/Code/User/keybindings.json: vscode/keybindings.json
    # IDEA
    ~/.ideavimrc: idea/ideavimrc
