# Settings
- defaults:
    link:
      create: true
      relink: true
      force: true # Swap original file

# TODO: ?
- clean: ["~"]

# Run shell commands
- shell:
    # Install submodules
   - [git submodule update --init --recursive, Installing submodules]
   # Install neovim
  #  - [./nvim/install.sh, Installing neovim things]

# Symlink files
- link:
    # bin
    ~/.bin:
      create: true
      path: bin
    ~/.bin/airport: /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport
    # Zsh
    ~/.zshrc:
      force: true
      path: zsh/zshrc.zsh
    ~/.zshrc.d:
      create: true
      path: zsh/
    ~/.config/karabiner.edn:
      create: true
      path: karabiner/karabiner.edn
    ~/.asdf: asdf
    ~/.zlogin: zsh/zlogin
    ~/.zshenv: zsh/zshenv
    ~/.zshkeys: zsh/zshkeys
    ~/.p10k.zsh: zsh/p10k.zsh
    ~/.tmux.conf: tmux/tmux.conf
    ~/.tmux.conf.local: tmux/tmux.conf.local
    ~/.yabairc: yabai/yabairc
    ~/.fonts:
      create: true
      path: local/fonts/
    ~/.doom.d: emacs
    ~/.config/starship.toml: config/starship.toml
    ~/.zshrc: zsh/zshrc.zsh
    ~/.zprofile: zsh/zprofile.zsh
    # Git
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
    # antibody
    ~/.antibody: config/antibody.txt
    # Hammerspoon
    ~/.hammerspoon:
      create: true
      path: hammerspoon
    # Doing
    ~/.doingrc: config/doing.yml
    # hyper.js
    ~/.hyper.js: config/hyper.js
    # Vim
    ~/.vimrc: vim/vimrc
    ~/.vimrc.bundles: vim/vimrc.bundles
    ~/.vimrc.local: vim/vimrc.local
    ~/.vimrc.bundles.local: vim/vimrc.bundles.local
    ~/.config/nvim: nvim/
    # VS Code
    ~/Library/Application Support/Code/User/settings.json: vscode/settings.json
    ~/Library/Application Support/Code/User/keybindings.json: vscode/keybindings.json
    # IDEA

    ~/.ideavimrc: idea/ideavimrc
    # Jupyter
    ~/Library/LaunchAgents/jupyter.plist: macos/jupyter.plist

- shell:
  - [ $(brew --prefix)/opt/fzf/install ]
  # - ["~/.emacs.d/bin/doom install"]
- go:
    - github.com/delicb/cliware

- rust:
    - stable:
        - targets:
            - x86_64-apple-darwin
            - x86_64-unknown-linux-gnu
        - components:
            - rust-analysis
            - rls
            - rust-src
- cargo:
    - cargo-watch
    - cargo-release
# Install asdf
- asdf:
      - plugin: python
        url: https://github.com/tuvistavie/asdf-python.git
        global: anaconda3-5.3.1
        versions:
          - anaconda3-5.3.1
      - plugin: nodejs
        url: https://github.com/asdf-vm/asdf-nodejs.git
        global: 12.15.0
        versions:
          - 12.15.0
      - plugin: ruby
        url: https://github.com/asdf-vm/asdf-ruby.git
        global: 2.6.4
        versions:
          - 2.6.4
      - plugin: golang
        url: https://github.com/kennyp/asdf-golang
        global: 1.13
        versions:
          - 1.13
      - plugin: elixir
        url: https://github.com/asdf-vm/asdf-elixir.git
        global: 1.10.1
        versions:
          - 1.10.1

- git:
    '~/.vim/bundle/Vundle.vim':
        url: 'https://github.com/VundleVim/Vundle.vim.git'
        description: "Vundle installation"

- shell:
    - "vim -c \"PluginInstall!\" -c \"q\" -c \"q\""

- vscodefile:
    # vscodefile
    file: vscode/vscodefile
    insiders: false

- brewfile:
      # This accepts the same options as `brew bundle` command:
      file: macos/Brewfile
