#!/usr/bin/env bash
# Bootstrap dotfiles configuration.

set -e

CONFIG=".install.conf.yaml"
VENDOR_DIR="./vendor"
DOTBOT_DIR="$VENDOR_DIR/dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive .

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" \
    --plugin-dir ${VENDOR_DIR}/dotbot-golang \
    --plugin-dir ${VENDOR_DIR}/dotbot-asdf \
    --plugin-dir ${VENDOR_DIR}/dotbot-vscode \
    --plugin-dir ${VENDOR_DIR}/dotbot-rust \
    --plugin-dir ${VENDOR_DIR}/dotbot-brewfile \
    -c "${CONFIG}" "${@}"
