#!/usr/bin/env bash
# Bootstrap dotfiles configuration.

set -e

CONFIG=".install.conf.yaml"
VENDOR_DIR="./vendor"
DOTBOT_DIR="$VENDOR_DIR/dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive .

if [ ! -f ${BASEDIR}/hammerspoon/Spoons/Lunette.spoon ]; then
    if [ ! -d ${BASEDIR}/hammerspoon/Spoons/Lunette ]; then
        /bin/echo "A" | unzip -qq ${BASEDIR}/hammerspoon/Spoons/Lunette/Spoons/Lunette.spoon.zip -d ${BASEDIR}/hammerspoon/Spoons
    fi
fi

if [ ! -f ${BASEDIR}/hammerspoon/Spoons/miro-windows-manager/MiroWindowsManager.spoon ]; then
    ln -sf ${BASEDIR}/hammerspoon/Spoons/miro-windows-manager/MiroWindowsManager.spoon ${BASEDIR}/hammerspoon/Spoons/MiroWindowsManager.spoon
fi

# --plugin-dir ${VENDOR_DIR}/dotbot-rust \
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" \
    --plugin-dir ${VENDOR_DIR}/dotbot-golang \
    --plugin-dir ${VENDOR_DIR}/dotbot-asdf \
    --plugin-dir ${VENDOR_DIR}/dotbot-vscode \
    --plugin-dir ${VENDOR_DIR}/dotbot-brewfile \
    --plugin-dir ${VENDOR_DIR}/dotbot-rust \
    -c "${CONFIG}" --verbose "${@}"
